version: '3'

services:
  db:
    container_name: dog-care-db-container
    image: mdillon/postgis:11-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./db_data:/var/lib/postgresql/data
    env_file:
      - ./set_db_env.env
  backend:
    container_name: dog-care-backend-container
    build:
      context: ../backend
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 5; done; python manage.py runserver_plus 0.0.0.0:8000 --cert-file server.crt'
    volumes:
      - ../backend/dog_care:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    user: ${CURRENT_UID}
